import java.security.MessageDigest
import org.gradle.api.artifacts.component.ModuleComponentIdentifier
import org.gradle.api.artifacts.dsl.LockMode

buildscript {
    val securityVersions = mapOf(
        "com.google.protobuf:protobuf-java" to "3.25.5",
        "com.google.protobuf:protobuf-kotlin" to "3.25.5",
        "io.netty" to "4.1.137.Final",
        "org.apache.commons:commons-compress" to "1.27.1",
        "org.apache.commons:commons-lang3" to "3.18.0",
        "org.apache.httpcomponents:httpclient" to "4.5.14",
        "org.bitbucket.b_c:jose4j" to "0.9.6",
        "org.bouncycastle:bcpkix-jdk18on" to "1.85",
        "org.bouncycastle:bcprov-jdk18on" to "1.85",
        "org.jdom:jdom2" to "2.0.6.1",
    )
    project.extra["dependencySecurityVersions"] = securityVersions
    configurations.configureEach {
        resolutionStrategy.eachDependency {
            val key = if (requested.group == "io.netty") {
                "io.netty"
            } else {
                "${requested.group}:${requested.name}"
            }
            securityVersions[key]?.let { secureVersion ->
                useVersion(secureVersion)
                because("audited version with fixes for the build-tool inventory")
            }
        }
    }
}

plugins {
    id("com.android.application") version "9.4.0" apply false
    id("com.android.library") version "9.4.0" apply false
    id("org.jetbrains.kotlin.plugin.compose") version "2.3.20" apply false
}

@Suppress("UNCHECKED_CAST")
val dependencySecurityVersions = extra["dependencySecurityVersions"] as Map<String, String>

allprojects {
    configurations.configureEach {
        if (name.endsWith("DependenciesMetadata")) {
            resolutionStrategy.deactivateDependencyLocking()
        }
        resolutionStrategy.eachDependency {
            val key = if (requested.group == "io.netty") {
                "io.netty"
            } else {
                "${requested.group}:${requested.name}"
            }
            dependencySecurityVersions[key]?.let { secureVersion ->
                useVersion(secureVersion)
                because("audited version with fixes for the build-tool inventory")
            }
        }
    }
}

subprojects {
    dependencyLocking {
        lockAllConfigurations()
        lockMode.set(LockMode.STRICT)
    }
}

val releaseRuntimeInventoryFile = layout.projectDirectory.file(
    "gradle/release-runtime/gradle.lockfile",
)
val releaseRuntimeInventoryFragments = subprojects.map { subproject ->
    val fragmentFile = layout.buildDirectory.file(
        "release-runtime-inventory/${subproject.name}.txt",
    )
    val fragmentTask = subproject.tasks.register("writeReleaseRuntimeDependencyInventoryFragment") {
        group = "dependency management"
        description = "Writes this project's release runtime dependency inventory fragment."
        outputs.file(fragmentFile)
        outputs.upToDateWhen { false }

        doLast {
            val coordinates = project.configurations
                .getByName("releaseRuntimeClasspath")
                .incoming
                .resolutionResult
                .allComponents
                .mapNotNull { component ->
                    (component.id as? ModuleComponentIdentifier)?.let { id ->
                        "${id.group}:${id.module}:${id.version}=releaseRuntimeClasspath"
                    }
                }
                .toSortedSet()
            val outputFile = fragmentFile.get().asFile
            outputFile.parentFile.mkdirs()
            outputFile.writeText(coordinates.joinToString(separator = "\n", postfix = "\n"))
        }
    }
    fragmentTask to fragmentFile
}

tasks.register("writeReleaseRuntimeDependencyInventory") {
    group = "dependency management"
    description = "Writes the exact external release runtime dependency inventory for OSV scanning."
    dependsOn(releaseRuntimeInventoryFragments.map { it.first })
    inputs.files(releaseRuntimeInventoryFragments.map { it.second })
    outputs.file(releaseRuntimeInventoryFile)
    outputs.upToDateWhen { false }

    doLast {
        val coordinates = releaseRuntimeInventoryFragments
            .flatMap { (_, fragmentFile) -> fragmentFile.get().asFile.readLines() }
            .filter(String::isNotBlank)
            .toSortedSet()
        val outputFile = releaseRuntimeInventoryFile.asFile
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            buildString {
                appendLine("# Generated by writeReleaseRuntimeDependencyInventory; do not edit manually.")
                coordinates.forEach(::appendLine)
                appendLine("empty=releaseRuntimeClasspath")
            },
        )
    }
}

tasks.register("verifyKotlinKaptAdvisoryGuard") {
    group = "verification"
    description = "Rejects build settings that expose the open Kotlin KAPT cache advisory path."
    doLast {
        check(!gradle.startParameter.isBuildCacheEnabled) {
            "Gradle build cache must remain disabled while GHSA-r937-wjx7-w2jp is open"
        }
        check(providers.gradleProperty("kapt.incremental.apt").orNull == "false") {
            "Incremental KAPT must remain disabled while GHSA-r937-wjx7-w2jp is open"
        }
        val kaptTasks = allprojects.flatMap { project ->
            project.tasks.names
                .filter { it.startsWith("kapt", ignoreCase = true) }
                .map { "${project.path}:$it" }
        }
        check(kaptTasks.isEmpty()) {
            "KAPT is not permitted while GHSA-r937-wjx7-w2jp is open: ${kaptTasks.sorted()}"
        }
    }
}

tasks.register("verifyVendoredProtocol") {
    group = "verification"
    description = "Verifies SHA-256 hashes of vendored protocol assets."
    doLast {
        fun verify(assetPath: String, hashPath: String) {
            val asset = file(assetPath)
            val expected = file(hashPath).readText().trim()
            val actual = MessageDigest.getInstance("SHA-256")
                .digest(asset.readBytes())
                .joinToString("") { "%02x".format(it) }
            check(actual == expected) {
                "Vendored protocol hash mismatch for $assetPath: expected $expected, got $actual"
            }
            println("Protocol asset verified: $assetPath $actual")
        }

        verify("protocol/vendor/notification/v1/envelope.proto", "protocol/SCHEMA_SHA256")
        verify("protocol/vendor/notification/v1/payload.proto", "protocol/PAYLOAD_SCHEMA_SHA256")
        verify("protocol/vendor/membership/v1/membership.proto", "protocol/MEMBERSHIP_SCHEMA_SHA256")
        verify("protocol/workspace-membership-v1.md", "protocol/MEMBERSHIP_SPEC_SHA256")
        verify(
            "protocol/test-vectors/workspace-membership-v1.json",
            "protocol/MEMBERSHIP_VECTOR_SHA256",
        )
        verify("protocol/encrypted-payload-v1.md", "protocol/PAYLOAD_SPEC_SHA256")
        verify(
            "protocol/test-vectors/encrypted-payload-v1.json",
            "protocol/PAYLOAD_VECTOR_SHA256",
        )
        verify("protocol/routing-header-v1.md", "protocol/ROUTING_HEADER_SPEC_SHA256")
        verify(
            "protocol/test-vectors/routing-header-v1.json",
            "protocol/ROUTING_HEADER_VECTOR_SHA256",
        )
        verify(
            "protocol/encrypted-envelope-v1.md",
            "protocol/ENCRYPTED_ENVELOPE_SPEC_SHA256",
        )
        verify(
            "protocol/test-vectors/encrypted-envelope-v1.json",
            "protocol/ENCRYPTED_ENVELOPE_VECTOR_SHA256",
        )
        verify("protocol/device-auth-frame-v1.md", "protocol/DEVICE_AUTH_SPEC_SHA256")
        verify(
            "protocol/transport-heartbeat-v1.md",
            "protocol/TRANSPORT_HEARTBEAT_SPEC_SHA256",
        )
        verify(
            "protocol/transport-credential-rotation-v1.md",
            "protocol/TRANSPORT_CREDENTIAL_ROTATION_SPEC_SHA256",
        )
        verify(
            "protocol/e2ee-identity-key-transition-v1.md",
            "protocol/E2EE_IDENTITY_TRANSITION_SPEC_SHA256",
        )
        verify(
            "protocol/test-vectors/e2ee-identity-key-transition-v1.json",
            "protocol/E2EE_IDENTITY_TRANSITION_VECTOR_SHA256",
        )
        verify(
            "protocol/test-vectors/device-auth-frame-v1.json",
            "protocol/DEVICE_AUTH_VECTOR_SHA256",
        )
        verify("protocol/relay-delivery-v1.md", "protocol/RELAY_DELIVERY_SPEC_SHA256")
        verify(
            "protocol/test-vectors/relay-delivery-v1.json",
            "protocol/RELAY_DELIVERY_VECTOR_SHA256",
        )
        verify(
            "protocol/trusted-device-pairing-v1.md",
            "protocol/TRUST_PAIRING_SPEC_SHA256",
        )
        verify(
            "protocol/test-vectors/trusted-device-pairing-v1.json",
            "protocol/TRUST_PAIRING_VECTOR_SHA256",
        )
    }
}
